# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          docker:
            - image: cimg/node:17.2.0
          # If you are using yarn, change the line below from "npm" to "yarn"
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
          command: npm run test
          name: Run tests