version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  dev_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
  test_my_app:
    jobs:
      - dev_and_test
